apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaopeso
spec:
   replicas: 3
   selector:
     matchLabels:
       app: conversaopeso
   template:
     metadata:
       labels:
         app: conversaopeso
     spec:
       containers:
         - name: conversaopeso
           image: labsampaio/conversaopeso:latest
           ports:
             - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: conversaopeso
spec: 
  selector: 
    app: conversaopeso
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: 30000
  type: NodePort
  
